#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' && github.sha || '' }}
  cancel-in-progress: true

jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_distribution.yml@main
    with:
      duckdb_version: 88277463aa86b998f241a0cd0f87ea647e749576
      ci_tools_version: 32eb753d9b660bf90bdca42652cf40c1ef64bf67
      extension_name: robust

  code-quality-check:
    name: Code Quality Check
    uses: duckdb/extension-ci-tools/.github/workflows/_extension_code_quality.yml@main
    with:
      duckdb_version: 88277463aa86b998f241a0cd0f87ea647e749576
      ci_tools_version: 32eb753d9b660bf90bdca42652cf40c1ef64bf67
      extension_name: robust
      format_checks: 'format;tidy'